### ISSUE TITLE
require('./App') has wrong capitalization 

### ISSUE THREAD

**Issue by pirm-in** [nicolashery/example-d3-react#2]
You might not have noticed because of your file system, but when i run _npm start_ on my linux i get the following error:

```
ERROR in ./src/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./app in /path/to/example-d3-react/src
 @ ./src/main.js 3:10-26
```

Changing line 3 in main.js like this 

```
var App = require('./App');
```

fixes the problem. Thank you for your nice example!

**Comment by kbrownell** [comment]
I also had to: npm install less@1.5.0.  Agreed, thanks for sharing your awesome work!

**Comment by nicolashery** [comment]
Thanks for letting me know!

Fixed in https://github.com/nicolashery/example-d3-react/commit/fefe41a8d0090c3acafdf89f791b80e677597163 and https://github.com/nicolashery/example-d3-react/commit/6ef274dff080b35bb5d99d538ba0384cb61c8d32
